[project]
name = "Phiwallpaper"
version = "v0.2.0-beta.1"
description = "基于Python的动态壁纸软件"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "infi-systray>=0.1.12.1",
    "opencv-python>=4.13.0.92",
    "pywin32>=311",
    "Pillow>=9.3.0",
    "psutil>=7.0.0",
    "pathlib>=1.0.1"
]
